"""Public-safe interplanetary trajectory models and transfer-design utilities."""

from aerognc.astrodynamics.bodies import CircularOrbitBody, KeplerianOrbitBody, PrimaryBody
from aerognc.astrodynamics.bplane import BPlaneTarget, target_b_plane
from aerognc.astrodynamics.dynamics import RestrictedNBodyModel
from aerognc.astrodynamics.ephemeris import (
    AnalyticalEphemeris,
    EphemerisProvider,
    EphemerisUnavailableError,
    SpiceEphemeris,
    TabulatedEphemeris,
)
from aerognc.astrodynamics.ephemeris_provider import (
    AnalyticalEphemerisProvider,
    CoverageAwareEphemeris,
    EphemerisCoverage,
    EphemerisCoverageError,
    EphemerisState,
    SpiceEphemerisProvider,
    TabulatedEphemerisProvider,
)
from aerognc.astrodynamics.finite_burn import (
    FiniteBurnExecution,
    execute_two_body_finite_burn,
)
from aerognc.astrodynamics.full_n_body import (
    FullNBodyModel,
    FullNBodyPropagation,
    MassiveBody,
    propagate_full_n_body,
)
from aerognc.astrodynamics.geometry import (
    EclipseResult,
    ElevationCrossing,
    GroundStationAccessResult,
    LineOfSightResult,
    OccultationResult,
    SphericalBodyGeometry,
    SphericalGroundStation,
    eclipse_state,
    ground_station_access,
    ground_station_elevation_rad,
    line_of_sight,
    spherical_occultation,
)
from aerognc.astrodynamics.kepler import (
    KeplerPropagation,
    propagate_universal,
    stumpff_c,
    stumpff_s,
)
from aerognc.astrodynamics.lambert import LambertSolution, solve_lambert_universal
from aerognc.astrodynamics.launch_window import (
    LaunchWindowCandidate,
    LaunchWindowOptimization,
    optimize_launch_window,
)
from aerognc.astrodynamics.maneuvers import (
    FiniteBurn,
    ImpulsiveManeuver,
    ManeuverFrame,
    SpacecraftManeuver,
    apply_impulsive_maneuver,
    available_delta_v_mps,
    finite_burn_derivative,
    ideal_propellant_used_kg,
    rtn_to_inertial_matrix,
    vector_in_inertial_frame,
)
from aerognc.astrodynamics.mission_design import (
    DifferentialCorrectionResult,
    GravityAssistDesign,
    PorkchopGrid,
    TransferOpportunity,
    compute_porkchop_grid,
    design_gravity_assist,
    evaluate_lambert_transfer,
    injection_delta_v_mps,
    refine_gravity_assist_times,
    search_gravity_assist,
)
from aerognc.astrodynamics.multirevolution import (
    MultiRevolutionLambertSolution,
    MultiRevolutionSearchResult,
    RankedTransferCandidate,
    search_lambert_transfers,
    solve_lambert_revolutions,
)
from aerognc.astrodynamics.orbital_elements import (
    ClassicalOrbitalElements,
    eccentric_to_true_anomaly,
    elements_to_state,
    solve_kepler_equation,
    state_to_elements,
)
from aerognc.astrodynamics.patched_conics import (
    HyperbolicPatch,
    OrbitAssistedTour,
    TourBurn,
    hyperbolic_patch,
    plan_orbit_assisted_tour,
)
from aerognc.astrodynamics.perturbations import (
    PerturbationSettings,
    hill_sphere_radius_m,
    j2_acceleration_mps2,
    laplace_sphere_of_influence_radius_m,
    optional_perturbation_acceleration_mps2,
    schwarzschild_acceleration_mps2,
    solar_radiation_pressure_acceleration_mps2,
)
from aerognc.astrodynamics.reference_frames import (
    HELIOS_ECLIPJ2000,
    J2000_EQUATORIAL,
    ReferenceFrameDefinition,
    ecliptic_to_equatorial_j2000_matrix,
    transform_inertial_state,
)
from aerognc.astrodynamics.time_systems import (
    TimeScaleEpoch,
    tai_minus_utc_s,
    utc_to_time_scales,
)
from aerognc.astrodynamics.transfers import (
    FlybyGeometry,
    HohmannTransfer,
    design_hohmann_transfer,
    evaluate_hyperbolic_flyby,
)

__all__ = [
    "HELIOS_ECLIPJ2000",
    "J2000_EQUATORIAL",
    "AnalyticalEphemeris",
    "AnalyticalEphemerisProvider",
    "BPlaneTarget",
    "CircularOrbitBody",
    "ClassicalOrbitalElements",
    "CoverageAwareEphemeris",
    "DifferentialCorrectionResult",
    "EclipseResult",
    "ElevationCrossing",
    "EphemerisCoverage",
    "EphemerisCoverageError",
    "EphemerisProvider",
    "EphemerisState",
    "EphemerisUnavailableError",
    "FiniteBurn",
    "FiniteBurnExecution",
    "FlybyGeometry",
    "FullNBodyModel",
    "FullNBodyPropagation",
    "GravityAssistDesign",
    "GroundStationAccessResult",
    "HohmannTransfer",
    "HyperbolicPatch",
    "ImpulsiveManeuver",
    "KeplerPropagation",
    "KeplerianOrbitBody",
    "LambertSolution",
    "LaunchWindowCandidate",
    "LaunchWindowOptimization",
    "LineOfSightResult",
    "ManeuverFrame",
    "MassiveBody",
    "MultiRevolutionLambertSolution",
    "MultiRevolutionSearchResult",
    "OccultationResult",
    "OrbitAssistedTour",
    "PerturbationSettings",
    "PorkchopGrid",
    "PrimaryBody",
    "RankedTransferCandidate",
    "ReferenceFrameDefinition",
    "RestrictedNBodyModel",
    "SpacecraftManeuver",
    "SphericalBodyGeometry",
    "SphericalGroundStation",
    "SpiceEphemeris",
    "SpiceEphemerisProvider",
    "TabulatedEphemeris",
    "TabulatedEphemerisProvider",
    "TimeScaleEpoch",
    "TourBurn",
    "TransferOpportunity",
    "apply_impulsive_maneuver",
    "available_delta_v_mps",
    "compute_porkchop_grid",
    "design_gravity_assist",
    "design_hohmann_transfer",
    "eccentric_to_true_anomaly",
    "eclipse_state",
    "ecliptic_to_equatorial_j2000_matrix",
    "elements_to_state",
    "evaluate_hyperbolic_flyby",
    "evaluate_lambert_transfer",
    "execute_two_body_finite_burn",
    "finite_burn_derivative",
    "ground_station_access",
    "ground_station_elevation_rad",
    "hill_sphere_radius_m",
    "hyperbolic_patch",
    "ideal_propellant_used_kg",
    "injection_delta_v_mps",
    "j2_acceleration_mps2",
    "laplace_sphere_of_influence_radius_m",
    "line_of_sight",
    "optimize_launch_window",
    "optional_perturbation_acceleration_mps2",
    "plan_orbit_assisted_tour",
    "propagate_full_n_body",
    "propagate_universal",
    "refine_gravity_assist_times",
    "rtn_to_inertial_matrix",
    "schwarzschild_acceleration_mps2",
    "search_gravity_assist",
    "search_lambert_transfers",
    "solar_radiation_pressure_acceleration_mps2",
    "solve_kepler_equation",
    "solve_lambert_revolutions",
    "solve_lambert_universal",
    "spherical_occultation",
    "state_to_elements",
    "stumpff_c",
    "stumpff_s",
    "tai_minus_utc_s",
    "target_b_plane",
    "transform_inertial_state",
    "utc_to_time_scales",
    "vector_in_inertial_frame",
]
